{
 "title": "Kubernetes Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Kubernetes Metrics - Cook API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Kubernetes Metrics - Order API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "App pods running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"order\", phase=\"Running\", pod=~\"tech-challenge-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - Application",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='order', pod=~'tech-challenge-.*'}[2m])) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"tech-challenge-.*\", resource=\"cpu\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage - Application",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace='order', pod=~'tech-challenge-.*'}) by (pod)"
    }
   ]
  },
  {
   "title": "Avg pod CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='order', pod=~'tech-challenge-.*'}[2m])) / sum(kube_pod_container_resource_requests{pod=~\"tech-challenge-.*\", resource=\"cpu\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Metrics - Payment API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Avg pod CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='payment', pod=~'tech-challenge-.*'}[2m])) / sum(kube_pod_container_resource_requests{pod=~\"tech-challenge-.*\", resource=\"cpu\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - Application",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='payment', pod=~'tech-challenge-.*'}[2m])) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"tech-challenge-.*\", resource=\"cpu\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage - Application",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace='payment', pod=~'tech-challenge-.*'}) by (pod)"
    }
   ]
  },
  {
   "title": "App pods running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"payment\", phase=\"Running\", pod=~\"tech-challenge-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX Ingress Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_pod=~\"ingress-nginx-controller.*\", controller_class=\"k8s.io/ingress-nginx\", controller_namespace=\"ingress-nginx\"}) ",
       "legendFormat": "nginx"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_pod=~\"ingress-nginx-controller.*\", controller_class=\"k8s.io/ingress-nginx\", controller_namespace=\"ingress-nginx\"}[2m])) ",
       "legendFormat": "nginx"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per second (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"(.*actuator.*|.*swagger-ui.*|.*api-docs.*)\"}[15s])) by (uri)"
      }
     ]
    },
    {
     "title": "Total of Requests",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{uri!~\"(.*actuator.*|.*swagger-ui.*|.*api-docs.*)\"}[5m])) by (uri)"
      }
     ]
    }
   ]
  }
 ]
}