prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'tech-challenge-microservices'
        scrape_interval: '15s'
        kubernetes_sd_configs:
          - role: 'endpoints'
        relabel_configs:
          - source_labels: ['__meta_kubernetes_service_name']
            action: 'keep'
            regex: 'tech-challenge-(cook|payment|order)-api-service'
          - source_labels: ['__meta_kubernetes_service_name']
            target_label: '__metrics_path__'
            replacement: '/actuator/prometheus'
          - source_labels: ['__meta_kubernetes_service_name']
            regex: 'tech-challenge-payment-api-service'
            target_label: '__metrics_path__'
            replacement: '/payment/actuator/prometheus'
          - source_labels: ['__meta_kubernetes_service_name']
            regex: 'tech-challenge-order-api-service'
            target_label: '__metrics_path__'
            replacement: '/order/actuator/prometheus'
          - source_labels: ['__meta_kubernetes_service_name']
            regex: 'tech-challenge-cook-api-service'
            target_label: '__metrics_path__'
            replacement: '/cook/v1/metrics'
      - job_name: 'ingress-nginx-metrics'
        metrics_path: '/metrics'
        kubernetes_sd_configs:
          - role: 'endpoints'
        relabel_configs:
          - source_labels: 
            - '__meta_kubernetes_service_name'
            action: 'keep'
            regex: 'ingress-nginx-controller-metrics'
          - source_labels: 
            - '__meta_kubernetes_namespace'
            action: 'keep'
            regex: 'ingress-nginx'
          - source_labels: 
            - '__meta_kubernetes_endpoint_port_name'
            action: 'keep'
            regex: 'metrics-metrics'
      - job_name: 'sonarqube'
        scrape_interval: '15s'
        metrics_path: '/sonarqube/api/monitoring/metrics'
        scheme: 'http'
        static_configs:
          - targets: 
            - 'sonarqube-sonarqube.monitoring.svc.cluster.local:9000'
        bearer_token: 'techchallenge-sonarqube-secret'

grafana:
  enabled: false

alertmanager:
  enabled: false

